# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    # run 10 copies of the current job in parallel

    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run split Cypress testes
        uses: cypress-io/github-action@v6
        continue-on-error: true
        #pass the machine index and the total number
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
        with:
           command: npm install
           
      - name: Upload Cypress report
        uses: actions/upload-artifact@v4
        with:
           name: mochawesome-report-${{ matrix.containers }}
           path: cypress/reports
 
  merge-reports:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkou repository
        uses: actions/checkout@v4
      
      - name: Download all reports
        uses: actions/download-artifact@v4
        with:
          name: mochawesome-report-*
          path: reports

      - name: Install mochawesome-merge and mochawesome-report-generator
        run: |
          npm install -g mochawesome-merge mochawesome-report-generator

      - name: Merge reports
        run: |
          mochawesome-merge reports/**/*.json > merged-report.json

      - name: Generate HTML report
        run: |
          marge merged-report.json --reportDir ./merged-report

      - name: Upload Merged Report
        uses: actions/upload-artifact@v4
        with:
          name: merged-mochawesome-report
          path: merged-report    
