name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        containers: [1/2, 2/2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Run split Cypress tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
        with:
          start: run --record --key your-key-here --parallel --group ${{ matrix.containers }}

      - name: Save Mochawesome reports
        uses: actions/upload-artifact@v2
        with:
          name: mochawesome-reports
          path: cypress/reports

  merge-reports:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Mochawesome reports
        uses: actions/download-artifact@v2
        with:
          name: mochawesome-reports
          path: cypress/reports

      - name: Merge Mochawesome reports
        run: npx mochawesome-merge cypress/reports/*.json > cypress/reports/report.json

      - name: Generate HTML report
        run: npx marge cypress/reports/report.json -f report -o cypress/reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v2
        with:
          name: html-report
          path: cypress/reports/report.html
