# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: |
          npm test
          echo "::group::Resumo dos Testes"
          TEST_RESULTS=$(npx cypress run --reporter json | jq -r '.stats | "Total: \(.tests), Passou: \(.passes), Falhou: \(.failures), Pendente: \(.pending)"')
          echo "::warning::Resultados dos Testes: $TEST_RESULTS"
          
          # Extrair números individuais
          TOTAL=$(echo $TEST_RESULTS | awk '{print $2}' | tr -d ',')
          PASSED=$(echo $TEST_RESULTS | awk '{print $4}' | tr -d ',')
          FAILED=$(echo $TEST_RESULTS | awk '{print $6}' | tr -d ',')
          PENDING=$(echo $TEST_RESULTS | awk '{print $8}')
          
          # Criar annotations individuais
          echo "::notice title=Total de Testes::$TOTAL"
          echo "::notice title=Testes Passados::$PASSED"
          
          if [ "$FAILED" -gt 0 ]; then
            echo "::error title=Testes Falhados::$FAILED"
          else
            echo "::notice title=Testes Falhados::$FAILED"
          fi
          
          if [ "$PENDING" -gt 0 ]; then
            echo "::warning title=Testes Pendentes::$PENDING"
          else
            echo "::notice title=Testes Pendentes::$PENDING"
          fi
          
          echo "::endgroup::"
        continue-on-error: true