name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install

      - name: Run split Cypress tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        env:
          SPLIT: ${{ strategy.job-total }}
          SPLIT_INDEX: ${{ strategy.job-index }}
        with:
          command: npm install

      - name: Upload Cypress report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report-${{ matrix.containers }}
          path: cypress/reports

  merge-reports:
    needs: cypress-run
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create reports directory
      run: mkdir -p reports

    - name: Download all reports
      run: |
        for i in {1..2}; do
          echo "Downloading mochawesome-report-${i}..."
          curl -sSfLJO https://github.com/brutastee55/NovoPadraPlard/actions/runs/9860301748/artifacts/mochawesome-report-${i}.zip || exit 1
          unzip -q mochawesome-report-${i}.zip -d reports/mochawesome-report-${i} || exit 1
          rm mochawesome-report-${i}.zip || exit 1
        done

    - name: Install mochawesome-merge and marge
      run: |
        npm install -g mochawesome-merge mochawesome-report-generator

    - name: Merge reports
      run: |
        mochawesome-merge reports/**/*.json > merged-report.json

    - name: Generate HTML report
      run: |
        npx marge merged-report.json --reportDir ./merged-report

    - name: Upload Merged Report
      uses: actions/upload-artifact@v4
      with:
        name: merged-mochawesome-report
        path: merged-report

